spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

camunda.bpm.admin-user:
  id: demo
  password: demo